#!/usr/bin/env python
from pathlib import Path
import shlex
import socket
import sys
from collections.abc import Iterable
import os

EVAL_TEXT = """
kehoitin_precmd() {
    export KEHOITIN_LAST_STATUS=$?
}
if (( !$precmd_functions[(Ie)kehoitin_precmd] )); then
    precmd_functions+=( kehoitin_precmd )
fi
PROMPT='$(_BINPATH_ prompt _INFILE_)'
"""

funcs = {"host": "%m", "pwd": "%~"}

host_abbr = {"localhost-live": "⌂"}

sepmap = {
    "angle": ("\ue0b0", True),
    "rev-angle": ("\ue0b2", False),
    "round": ("\ue0b4", True),
    "rev-round": ("\ue0b6", False),
    "downslope": ("\ue0b8", True),
    "rev-downslope": ("\ue0ba", False),
    "slope": ("\ue0bc", True),
    "rev-slope": ("\ue0be", False),
}


def func_host() -> str:
    hostname = socket.gethostname()
    return hostname
    # return host_abbr.get(hostname, hostname)


def func_git_branch() -> str:
    root = Path.cwd()
    gitdir = None
    for d in [root] + list(root.parents):
        if (d / ".git").exists():
            gitdir = d / ".git"
            break
    if not gitdir:
        return ""

    x = None
    if (gitdir / "rebase-merge").exists():
        x = "REBASE"
    elif (gitdir / "rebase-apply").exists():
        x = "REBASE"
    elif (gitdir / "MERGE_HEAD").exists():
        x = "MERGING"
    elif (gitdir / "BISECT_LOG").exists():
        x = "BISECTING"

    head = (gitdir / "HEAD").read_text().strip()
    if head.startswith("ref:"):
        if head.startswith("ref: refs/heads/"):
            head = head[16:]
    else:
        head = head[:7]

    if x:
        head = f"{head}:{x}"

    return head


def func_default() -> str:
    return "--"


def separator(ch: str) -> tuple[str, bool]:
    return sepmap[ch]


class PromptBuilder:
    def __init__(self) -> None:
        self.fg: str | None = None
        self.bg: str | None = None
        self.spans: list[str] = []
        self.commands: list[tuple[str, str]] = []

    def set_fg(self, fg: str) -> None:
        self.commands.append(("fg", fg))

    def set_bg(self, bg: str) -> None:
        self.commands.append(("bg", bg))

    def set_fg_from_bg(self) -> None:
        self.commands.append(("fg_from_bg", ""))

    def add_text(self, text: str) -> None:
        self.commands.append(("text", text))

    def add_prompt(self, builder: "PromptBuilder") -> None:
        self.commands += builder.commands

    def get(self) -> str:
        fg = ""
        bg = ""
        spans: list[str] = []
        for cmd, arg in self.commands:
            if cmd == "fg":
                if arg != fg:
                    fg = arg
                    if fg == "clear":
                        spans.append("%f")
                    else:
                        spans += ["%F{", fg, "}"]
            elif cmd == "bg":
                if arg != bg:
                    bg = arg
                    if bg == "clear":
                        spans.append("%k")
                    else:
                        spans += ["%K{", bg, "}"]
            elif cmd == "fg_from_bg":
                arg = bg
                if arg != fg:
                    fg = arg
                    if fg == "clear":
                        spans.append("%f")
                    else:
                        spans += ["%F{", fg, "}"]
            else:
                spans.append(arg)
        return "".join(spans)


def evaluate_condition(cond: str) -> bool:
    if cond.startswith("!"):
        return not evaluate_condition(cond[1:])
    if cond == "true":
        return True
    if cond == "false":
        return False
    if cond == "git":
        return func_git_branch() != ""
    if cond == "success":
        status = os.getenv("KEHOITIN_LAST_STATUS")
        return status is None or status == "0"

    raise ValueError("invalid condition")


def read_block(lines: Iterable[str]) -> PromptBuilder:
    out = PromptBuilder()

    for line in lines:
        tokens = shlex.split(line)
        if not tokens:
            continue
        elif tokens[0] == "text":
            out.add_text(tokens[1])
        elif tokens[0] == "color":
            fg = tokens[1]
            bg = tokens[2]
            if len(tokens) > 3:
                symbol, forward = separator(tokens[3])
                if forward:
                    out.set_fg_from_bg()
                    out.set_bg(bg)
                else:
                    out.set_fg(bg)
                out.add_text(symbol)
            out.set_fg(fg)
            out.set_bg(bg)
        elif tokens[0] == "func":
            name = tokens[1]
            if name == "cwd":
                out.add_text(str(Path.cwd()))
            elif name == "host":
                out.add_text(func_host())
            elif name == "git-branch":
                out.add_text(func_git_branch())
            else:
                out.add_text(f"(invalid function {name})")
        elif tokens[0] == "if":
            cond = tokens[1]
            block = read_block(lines)
            try:
                if evaluate_condition(cond):
                    out.add_prompt(block)
            except ValueError:
                out.add_text(f"(invalid condition {cond})")
        elif tokens[0] == "end":
            break
        else:
            out.add_text(f"(invalid token {tokens[0]})")

    return out


def interpret(lines: Iterable[str]) -> str:
    return read_block(lines).get()


def show_usage() -> None:
    print("usage: kehoitin prompt|eval <file>")


def main() -> None:
    if len(sys.argv) != 3:
        show_usage()
    elif sys.argv[1] == "prompt":
        infile = sys.argv[2]
        with open(infile, "r") as fp:
            print(interpret(fp), end="")
    elif sys.argv[1] == "eval":
        infile = sys.argv[2]
        print(
            EVAL_TEXT.replace("_BINPATH_", str(Path(sys.argv[0]).absolute())).replace(
                "_INFILE_", str(Path(infile).absolute())
            )
        )
    else:
        show_usage()
        sys.exit(2)


if __name__ == "__main__":
    main()
