#!/usr/bin/env python
from pathlib import Path
import shlex
import socket
import sys

funcs = {"host": "%m", "pwd": "%~"}

host_abbr = {"localhost-live": "⌂"}

sepmap = {
    "angle": ("\ue0b0", True),
    "rev-angle": ("\ue0b2", False),
    "round": ("\ue0b4", True),
    "rev-round": ("\ue0b6", False),
    "downslope": ("\ue0b8", True),
    "rev-downslope": ("\ue0ba", False),
    "slope": ("\ue0bc", True),
    "rev-slope": ("\ue0be", False),
}


def func_host():
    hostname = socket.gethostname()
    return hostname
    # return host_abbr.get(hostname, hostname)


def func_git_branch():
    root = Path.cwd()
    gitdir = None
    for d in [root] + list(root.parents):
        if (d / ".git").exists():
            gitdir = d / ".git"
            break
    if not gitdir:
        return ""

    x = None
    if (gitdir / "rebase-merge").exists():
        x = "REBASE"
    elif (gitdir / "rebase-apply").exists():
        x = "REBASE"
    elif (gitdir / "MERGE_HEAD").exists():
        x = "MERGING"
    elif (gitdir / "BISECT_LOG").exists():
        x = "BISECTING"

    head = (gitdir / "HEAD").read_text().strip()
    if head.startswith("ref:"):
        if head.startswith("ref: refs/heads/"):
            head = head[16:]
    else:
        head = head[:7]

    if x:
        head = f"{head}:{x}"

    return head


def func_default():
    return "--"


def separator(ch):
    return sepmap[ch]


class PromptBuilder:
    def __init__(self):
        self.fg = None
        self.bg = None
        self.spans = []

    def set_color(self, fg, bg):
        if fg is not None and fg != self.fg:
            self.fg = fg
            if fg == "clear":
                self.spans.append("%f")
            else:
                self.spans += ["%F{", fg, "}"]
        if bg is not None and bg != self.bg:
            self.bg = bg
            if bg == "clear":
                self.spans.append("%k")
            else:
                self.spans += ["%K{", bg, "}"]

    def add(self, *args):
        self.spans += args

    def get(self):
        return "".join(self.spans)


def interpret(input_lines):
    out = PromptBuilder()

    for line in input_lines:
        tokens = shlex.split(line)
        if not tokens:
            continue
        elif tokens[0] == "text":
            out.add(tokens[1])
        elif tokens[0] == "color":
            fg = tokens[1]
            bg = tokens[2]
            if len(tokens) > 3:
                symbol, forward = separator(tokens[3])
                if forward:
                    out.set_color(out.bg, bg)
                else:
                    out.set_color(bg, out.bg)
                out.add(symbol)
            out.set_color(fg, bg)
        elif tokens[0] == "func":
            name = tokens[1]
            if name == "cwd":
                out.add(str(Path.cwd()))
            elif name == "host":
                out.add(func_host())
            elif name == "git-branch":
                out.add(func_git_branch())
            else:
                out.add(f"(invalid function {name})")

    return out.get()


def show_usage():
    print("usage: kehoitin interpret")


def main():
    if len(sys.argv) != 2:
        show_usage()
    elif sys.argv[1] == "interpret":
        print(interpret(sys.stdin), end="")
    else:
        show_usage()
        sys.exit(2)


if __name__ == "__main__":
    main()
